- name: Setup Theos
        run: |
          rm -rf /opt/theos
          git clone --depth 1 https://github.com/theos/theos.git /opt/theos
          git clone --depth 1 https://github.com/theos/sdks.git /opt/theos/sdks
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
